import { differenceInDays, startOfDay } from 'date-fns'
import { SlotModel } from '../../../models/slot.model'

// ============================================================================
// TYPES
// ============================================================================

/**
 * Result of partitioning slots by visibility based on container constraints.
 * 
 * This structure allows the UI layer to:
 * 1. Render only visible slots
 * 2. Show "+N more" indicators per day column
 * 3. Access hidden slots for popover/modal display
 */
export interface SlotVisibilityResult {
  /** Slots that fit within the available rows */
  visibleSlots: SlotModel[]

  /** Slots that exceed the row limit and should be hidden */
  hiddenSlots: SlotModel[]

  /** 
   * Count of hidden events per day of the week.
   * Index 0 = first day of week (Sunday or Monday depending on locale)
   * Index 6 = last day of week
   * 
   * @example
   * // overflowPerDay = [0, 0, 2, 1, 0, 0, 0]
   * // means: Wednesday has 2 hidden, Thursday has 1 hidden
   */
  overflowPerDay: number[]
}

// ============================================================================
// CONSTANTS
// ============================================================================

const DAYS_IN_WEEK = 7

// ============================================================================
// MAIN FUNCTION
// ============================================================================

/**
 * Partitions slots into visible and hidden based on the maximum number of rows
 * that can fit in the container.
 * 
 * ## How it works:
 * 
 * 1. Each slot has a `zIndex` which represents its row position (1-indexed).
 *    - zIndex 1 = Row 0 (top row)
 *    - zIndex 2 = Row 1
 *    - etc.
 * 
 * 2. If a slot's zIndex exceeds maxRows, the entire slot is hidden.
 *    This ensures multi-day events don't partially render.
 * 
 * 3. For hidden slots, we count how many events are hidden per day column.
 *    This allows showing "+N more" indicators in each affected day.
 * 
 * ## Visual Example:
 * 
 * ```
 * maxRows = 2
 * 
 *           Mon   Tue   Wed   Thu   Fri
 *          ┌─────┬─────┬─────┬─────┬─────┐
 * Row 0    │  A  │  A  │  A  │     │     │  visible (zIndex=1)
 *          ├─────┼─────┼─────┼─────┼─────┤
 * Row 1    │     │  B  │  B  │  B  │     │  visible (zIndex=2)
 *          ├─────┴─────┴─────┴─────┴─────┤ ← maxRows limit
 * Row 2    │     │     │  C  │     │     │  HIDDEN (zIndex=3)
 *          └─────┴─────┴─────┴─────┴─────┘
 * 
 * overflowPerDay = [0, 0, 1, 0, 0, 0, 0]
 *                           ↑ Wed shows "+1 more"
 * ```
 * 
 * @param slots - All slots generated by sliceEventsByWeek
 * @param maxRows - Maximum number of rows that fit in the container
 * @param weekStart - Start date of the week (used to calculate day indices)
 * @returns Partitioned slots with overflow counts per day
 */
export function partitionSlotsByVisibility(
  slots: SlotModel[],
  maxRows: number,
  weekStart: Date
): SlotVisibilityResult {
  const visibleSlots: SlotModel[] = []
  const hiddenSlots: SlotModel[] = []
  const overflowPerDay: number[] = new Array(DAYS_IN_WEEK).fill(0)

  // Normalize week start to beginning of day for consistent comparisons
  const normalizedWeekStart = startOfDay(weekStart)

  for (const slot of slots) {
    // zIndex is 1-indexed (row 0 has zIndex 1)
    // A slot is visible if its row fits within maxRows
    const isVisible = slot.zIndex <= maxRows

    if (isVisible) {
      visibleSlots.push(slot)
    } else {
      hiddenSlots.push(slot)

      // Calculate which days this hidden slot spans
      // and increment the overflow counter for each affected day
      incrementOverflowForSlotDays(slot, normalizedWeekStart, overflowPerDay)
    }
  }

  return { visibleSlots, hiddenSlots, overflowPerDay }
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Increments the overflow counter for each day that a slot occupies.
 * 
 * This ensures that the "+N more" indicator correctly reflects
 * all hidden events affecting each day column.
 * 
 * @param slot - The hidden slot
 * @param weekStart - Normalized start of the week
 * @param overflowPerDay - Array to mutate with incremented counts
 */
function incrementOverflowForSlotDays(
  slot: SlotModel,
  weekStart: Date,
  overflowPerDay: number[]
): void {
  // Calculate day indices (0-6) within the week
  const startDayIndex = differenceInDays(startOfDay(slot.start), weekStart)
  const endDayIndex = differenceInDays(startOfDay(slot.end), weekStart)

  // Clamp indices to valid range [0, 6]
  // This handles edge cases where slot dates might extend beyond the week
  const safeStartDay = Math.max(0, Math.min(startDayIndex, DAYS_IN_WEEK - 1))
  const safeEndDay = Math.max(0, Math.min(endDayIndex, DAYS_IN_WEEK - 1))

  // Increment counter for each day the slot spans
  for (let day = safeStartDay; day <= safeEndDay; day++) {
    overflowPerDay[day]++
  }
}
